import * as THREE from 'three';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/loaders/GLTFLoader.js';
const canvas=document.querySelector('#canvas3d'),scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x02070d,.012);
const camera=new THREE.PerspectiveCamera(42,1,.001,100000),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.minDistance=.1;controls.maxDistance=100000;
scene.add(new THREE.HemisphereLight(0x9eeaff,0x030811,2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(5,8,6);scene.add(key);const blue=new THREE.PointLight(0x19d9ff,12,100);blue.position.set(-4,2,4);scene.add(blue);const blue2=new THREE.PointLight(0x2678ff,9,100);blue2.position.set(5,-2,-4);scene.add(blue2);
let model=null,wire=false;
function frame(o){const box=new THREE.Box3().setFromObject(o),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());o.position.sub(center);const m=Math.max(size.x,size.y,size.z),d=Math.max(m*1.75,1);camera.position.set(d*.85,d*.55,d);camera.near=Math.max(d/1000,.001);camera.far=Math.max(d*100,1000);camera.updateProjectionMatrix();controls.target.set(0,0,0);controls.update()}
new GLTFLoader().load('./cpuramssd.glb',g=>{model=g.scene;scene.add(model);frame(model);document.querySelector('#loader').classList.add('hide');bootSound()},undefined,e=>{console.error(e);document.querySelector('#loader b').textContent='SYSTEM ERROR';document.querySelector('#loader span').textContent='หา cpuramssd.glb ไม่พบ หรือโหลดโมเดลไม่สำเร็จ'});
function resize(){const r=canvas.getBoundingClientRect();camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}addEventListener('resize',resize);resize();
document.querySelector('#auto').onclick=e=>{controls.autoRotate=!controls.autoRotate;controls.autoRotateSpeed=1.6;e.currentTarget.classList.toggle('active',controls.autoRotate);clickSound()};
document.querySelector('#wire').onclick=e=>{wire=!wire;if(model)model.traverse(o=>{if(o.isMesh){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.wireframe=wire)}});e.currentTarget.classList.toggle('active',wire);scanSound()};document.querySelector('#reset').onclick=()=>{if(model){frame(model);clickSound()}};
const data={cpu:['CPU / PROCESSOR','MODULE 01','CPU','Central Processing Unit','หน่วยประมวลผลกลาง ทำหน้าที่คำนวณและควบคุมการทำงานหลักของระบบ','PROCESSING','CPU'],ram:['RAM / MEMORY','MODULE 02','RAM','Random Access Memory','หน่วยความจำชั่วคราวสำหรับข้อมูลที่ระบบกำลังใช้งาน เพื่อให้เข้าถึงข้อมูลได้รวดเร็ว','MEMORY','RAM'],ssd:['SSD / STORAGE','MODULE 03','SSD','Solid State Drive','อุปกรณ์จัดเก็บข้อมูลแบบแฟลชที่ให้การเข้าถึงข้อมูลรวดเร็ว','STORAGE','SSD']};
document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{document.querySelectorAll('.card').forEach(x=>x.classList.remove('active'));c.classList.add('active');const d=data[c.dataset.key];['tag','num','orb','title','desc','role','type'].forEach((id,i)=>document.querySelector('#'+id).textContent=d[i]);clickSound();document.querySelector('.info-panel').animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:380,easing:'ease-out'})});
let audio=null,soundOn=true;function ctx(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}function tone(freq,dur,type='sine',gain=.035){if(!soundOn)return;const a=ctx(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,a.currentTime);g.gain.setValueAtTime(gain,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}function clickSound(){tone(620,.055,'square',.018);setTimeout(()=>tone(980,.045,'sine',.012),25)}function scanSound(){tone(180,.16,'sawtooth',.018);setTimeout(()=>tone(520,.1,'sine',.014),70)}function bootSound(){if(soundOn){tone(140,.2,'sine',.02);setTimeout(()=>tone(320,.15,'sine',.018),100);setTimeout(()=>tone(720,.2,'sine',.015),190)}}document.querySelector('#sound').onclick=e=>{soundOn=!soundOn;e.textContent=soundOn?'🔊':'🔇';if(soundOn)clickSound()};
(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
